import {
  BookOpen,
  Calculator,
  Languages,
  FlaskConical,
  Zap,
  Leaf,
  History,
  Globe,
  Landmark,
  Grid,
  Dice1 as Dice,
  Computer,
  Home,
  BookOpenCheck,
  StickyNote,
  Brain,
  AlertTriangle,
  Star,
  Layers,
  Play,
  TrendingUp,
  LineChart,
  Network,
  Plus,
  Edit,
  Trash2,
  Save,
  Upload,
  X,
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  Clock,
  Target,
  Lightbulb,
  Menu,
  Settings,
  type LucideProps,
} from 'lucide-react';

export const iconMap: Record<string, React.ElementType> = {
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'calculator': Calculator,
  'languages': Languages,
  'flask': FlaskConical,
  'zap': Zap,
  'leaf': Leaf,
  'history': History,
  'globe': Globe,
  'landmark': Landmark,
  'grid': Grid,
  'dice': Dice,
  'computer': Computer,
  'home': Home,
  'sticky-note': StickyNote,
  'brain': Brain,
  'alert-triangle': AlertTriangle,
  'star': Star,
  'layers': Layers,
  'play': Play,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  'network': Network,
  'plus': Plus,
  'edit': Edit,
  'trash2': Trash2,
  'save': Save,
  'upload': Upload,
  'x': X,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'check-circle2': CheckCircle2,
  'clock': Clock,
  'target': Target,
  'lightbulb': Lightbulb,
  'menu': Menu,
  'settings': Settings,
};

interface IconProps extends Omit<LucideProps, 'name'> {
  name: string;
}

export function Icon({ name, size = 24, className, ...props }: IconProps) {
  const IconComponent = iconMap[name] || BookOpen;
  return <IconComponent size={size} className={className} {...props} />;
}
